
package client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExampleServer", targetNamespace = "http://jaxws.pl/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ExampleServer {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://jaxws.pl/ExampleServer/getStringARequest", output = "http://jaxws.pl/ExampleServer/getStringAResponse")
    public String getStringA();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://jaxws.pl/ExampleServer/getStringBRequest", output = "http://jaxws.pl/ExampleServer/getStringBResponse")
    public String getStringB();

}
