/**
 * Generated by wsimport cmd call
 * 1. Publish service using class Publisher from first project
 * 2. Run in cmd: wsimport -keep -p client http://localhost:9876/ts?wsdl
 * 
 * For localy existing wsdl document call: wsimport -keep -p client ts.wsdl
 * Remember to add jdk/bin path to path system variables!
 */
package client;